### ISSUE TITLE
More base themes

### ISSUE THREAD

**Issue by browniebroke** [fabiocaccamo/django-admin-interface#15]
This Django app is amazing, such a great idea. We have several sites running with Django and we are starting using it to avoid confusion between sites and environments (local/test/live...). For my use case, it would make this even easier to deploy if there were a few more themes built in. 

I'm no designer so my first experimentations were a bit disappointing. I ended up with a theme inspired by [Bootstrap's docs](https://getbootstrap.com/) site, and I'd happily contribute back here. Would you be open to receive more themes? I was thinking of adding a fixtures that one would optionally load using:
```
python manage.py loaddata super_duper_theme.json
```
Then add a screenshot somewhere to document the theme's existence in the README? Do you have more docs somewhere?

**Comment by browniebroke** [comment]
Here is a preview:
![screencapture-localhost-8000-admin-admin_interface-theme-3-change-1494952716110](https://cloud.githubusercontent.com/assets/861044/26117454/883a454e-3a5e-11e7-9c81-65d2b3b13ab9.png)

**Comment by fabiocaccamo** [comment]
Hi @browniebroke, 
I'm glad that you like this app!

Yes, I already thought to support more default themes. 
Feel free to send me some more themes specifying where the style comes from (such as Bootstrap docs).

I think that the roadmap could include:
- Support more default themes by default
- Improve documentation (add a video and more screenshot desktop and mobile)
- Add import/export for themes ?! (but I'm not sure about this because it could be dangerous for backward compatibility)
- Support more 3rd parties apps

Have you checked the new related-modal? I'm very proud of that! 🎉

**Comment by browniebroke** [comment]
> Have you checked the new related-modal? I'm very proud of that! 🎉
You can be, it's awesome 👍  Didn't see it at first

**Comment by browniebroke** [comment]
Regarding the import/export, my first thoughts was to integrate with django-import-export, but it depends on tablib, which itself depends on a few things.

Otherwise, as a user, I like the way [it's done in Slack](http://slackthemes.net/). I think it could be emulated with a "quick import" action, like below:

![quick-import](https://cloud.githubusercontent.com/assets/861044/26121635/d82a03e2-3a6c-11e7-849d-c1e92e463605.png)

When clicked, it gives a page with a single field that may be copy/pasted easily from other places:

![quick-import-action](https://cloud.githubusercontent.com/assets/861044/26121701/097bb666-3a6d-11e7-9900-ad901fdd4142.png)

**Comment by fabiocaccamo** [comment]
Added Bootstrap and Foundation themes installable as fixtures, check the `0.4.5` version.

**Comment by browniebroke** [comment]
Thanks, looks good. As far as I'm concerned I'm happy to close this, which was more about _how to_ add more rather than purely adding more :-)
