### ISSUE TITLE
Dashboard feature

### ISSUE THREAD

**Issue by Ladet02** [fabiocaccamo/django-admin-interface#235]
When building django admin apps, it is usually nice to have a custom dashboard to display extra data.

Take a look a `django-unfold` package and see how that is achieved, it'll be nice to have something similar.

<a href="https://dashboard.polar.sh/fabiocaccamo/django-admin-interface/issues/235">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/235/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/django-admin-interface/issues/235/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
sorry for the question, but why don't you use `django-unfold` instead?

**Comment by merwok** [comment]
django-admin-interface is focused on providing only UI and UX improvements; other projects add functionality (like filters or action buttons); it seems that django-unfold does both: it’s styling based on tailwindcss and features for filters and dashboard page.  So I understand the request to be from someone who wants django-admin-interface style rather than django-unfold, but also the dashboard feature from the latter.

Unless I’m mistaken, the design of this project is to improve only UI/UX, and let people use other projects to enhance the admin.  There are many such projects: add links and custom actions and custom button links in admin list, add custom widgets in admin edit page, add full custom pages for a certain model or with global stats and graphs.  There can’t (and shouldn’t) be one project that subsumes all of these.

**Comment by fabiocaccamo** [comment]
> Unless I’m mistaken, the design of this project is to improve only UI/UX, and let people use other projects to enhance the admin. There are many such projects: add links and custom actions and custom button links in admin list, add custom widgets in admin edit page, add full custom pages for a certain model or with global stats and graphs. There can’t (and shouldn’t) be one project that subsumes all of these.

Exactly, if in the future there will be some good sponsor behind this project I will think to push it to a next level, but for now it's ok as it is.
