### ISSUE TITLE
Environment colors are backward

### ISSUE THREAD

**Issue by merwok** [fabiocaccamo/django-admin-interface#56]
Hello!  I noticed the fun little favicon change in the latest release.

I used to do something similar with django-admin-env notice¹ before I found django-admin-interface.  However, the colors I configured went in the opposite directions than the ones here: blue or green for test/dev envs, orange for staging (be careful but not real site), red for prod (be careful! this is the important one).

¹ https://github.com/dizballanze/django-admin-env-notice#screenshots

Would you consider either changing the colors, or making them customizable by the site (either statically in django setings, or as part of the theme object)?

Related request: could there be a checkbox in the theme to opt-in/opt-out of the favicon modification (in case people already have different favicons per env, or if the circle makes the icon not pretty)

Thanks for considering this!

**Comment by fabiocaccamo** [comment]
Hi @merwok, 
as always thanks for your feedback and suggestions.

**About env colors:**
I added the colors in this order because clients sometimes continue to use the staging admin also after the site has been published and they tell "*I don't see changes*", so my idea was:
- **red** - this is the dev env, don't make changes here
- **green** - this is the right place to make changes

Now, I'm confused, because I agree with your feedback too, at this point it's a question of perspective.

There are different ways to solve this:
- Remove current env presets and add 2 fields: env_name, env_color
- Add fields to customize color of each env
- Add settings to customize color of each env: I don't like this solution because all the package don't use settings, but just the admin interface to customize itself.

Personally I would opt for the first solution, which one do you prefer?

Do you prefer the env badge or the big horizontal bar like in `django-admin-env-notice`?

**About env badge in favicon:**
I agree, I will do it soon.

**Comment by merwok** [comment]
Honestly the big bar was a little intense!  Now I like it better with «staging» in the right info + I name the site «Blabla Admin — staging».  I think I would also like the favicon color (haven’t deployed that version yet), and ask my coworkers what they think.

My preference would be option 1.  Then all workflows are supported: dev and prod, dev/test/qa/staging/prod, blue/green deployments, développement/pré-prod/production, etc. :)

**Comment by fabiocaccamo** [comment]
@merwok just another question: in the admin, the setting relative to the badge visibility in the favicon where should be added? in the favicon fieldset or in the env fieldset? Could you ask an opinion to your coworkers too?

**Comment by merwok** [comment]
I chatted with my designer coworker.  The recommendation is to have all options to the Environment section:

- Environment: char field
- Color: color field, can be blank
- checkbox Visible in admin header
- checkbox Add marker to favicon
