### ISSUE TITLE
Import external CSS

### ISSUE THREAD

**Issue by zuck** [fabiocaccamo/django-admin-interface#63]
At the moment, inline CSS are supported using the `css` attribute inside the JSON configuration file.

It would be great to have the possibility to also import an external CSS file.

**Comment by fabiocaccamo** [comment]
@zuck thanks for the suggestion, I think it is an useful feature and it could be extended to external js too.
I will add it in the next release, if you have any other idea feel free to suggest it.

**Comment by merwok** [comment]
Ping here!  I could try making a PR if that helps.

**Comment by fabiocaccamo** [comment]
@merwok as you can see [here](https://github.com/fabiocaccamo/django-admin-interface/blob/master/admin_interface/models.py#L249) there is an old unused field that in the past was used to store custom extra css.

Now the necessity seems to be to have the possibility to upload a custom css file and why not, also a custom js file.
To be very flexible the best solution would be to add an additional model with a css/js file using a foreign key to the theme, but I think that this solutions would go over engineering the db for doing a simple thing. So, I would add two fields to the theme model: `extra_css` and `extra_js` (with file extension validator).

Let me know what do you think about it.

**Comment by merwok** [comment]
I think I misunderstood the original request!

I don’t want to import extra CSS; I already do customizations that I need (mostly on object add/edit page) with extra JS and CSS in overriden `admin/change_form.html` templates.  What I’d like is to move all the admin-interface CSS from the HTML template into a CSS template, so that the HTML pages only need `link rel=stylesheet`.  It would make the source shorter (good for view source!) and let the browser cache the stylesheet (using the appropriate cache headers based on a checksum or version, for invalidation).

**Comment by fabiocaccamo** [comment]
@9mido see #93

**Comment by fabiocaccamo** [comment]
@zuck the solution suggested by @merwok solves your problems?

If not, could you be more specific about what you would like to do but you can't do?
