### ISSUE TITLE
Calendar widget unexpected behavior in scrollable inlines

### ISSUE THREAD

**Issue by Duxa98** [fabiocaccamo/django-admin-interface#81]
**Python version**
Python 3.8.2

**Django version**
Django 2.2.12

**Package version**
0.12.1

In scrollable tabular inline calendar widget spawn not near the calendar button.

before scrolling:
![before_scrolling](https://user-images.githubusercontent.com/12458457/81399962-b76e2f80-9134-11ea-9b1d-e8e903d1280f.png)

after scrolling:
![after_scrolling](https://user-images.githubusercontent.com/12458457/81399987-c2c15b00-9134-11ea-9259-2ff03eb0afbc.png)

**Comment by fabiocaccamo** [comment]
@Duxa98 thank you for reporting this.

Could you try to:
- remove `admin_interface` from `settings.INSTALLED_APPS`
- run `collectstatic` 
- check if the calendar widget behavior is correct or not

**Comment by Duxa98** [comment]
@fabiocaccamo It has the same behavior without app, but only with low window size. In my case it works correct:
![](https://user-images.githubusercontent.com/12458457/81662410-2fdf3400-9446-11ea-9e1f-2f193fbfbcf7.png)

It looks the same when I remove admin-interface-fix.css from base_site.html

**Comment by fabiocaccamo** [comment]
@Duxa98 thanks for reporting this.
I investigated the problem and the cause is this css rule in `admin-interface-fix.css`:
```css
/* begin fix restrict tabular-inline horizontal-scroll to inline-group instead of whole page */
.admin-interface .inline-group[data-inline-type="tabular"] {
    overflow-x: auto;
}
/* end fix */
```
This rule is very useful to prevent whole body horizontal scroll when a tabular-inline has horizontal overflow, but with this rule django doesn't position the date picker and the time picker correctly (because it uses the absolute x position of the element).

You can avoid this behavior by placing the datetime field at the beginning of the inline row.

Frankly I don't know how to proceed to fix this, the only possible solution would be to override the js that places the date/time pickers to position them calculating the container scroll left offset, but overrinding the js is very dangerous and I would avoid to do it if possible.

Have you any idea?

**Comment by fabiocaccamo** [comment]
@Duxa98 any feedback?

**Comment by Duxa98** [comment]
@fabiocaccamo I place the datetime field at the beginning of the row, thanks for advice.
